export type SignalType =
  | "DEXBOOST_PAID"
  | "DEXAD_PAID"
  | "DEXBAR_PAID"
  | "CTO"
  | "UPDATE_SOCIAL"
  | "PRICE_UP"
  | "ATH"
  | "KEY_MC"

export type TokenRow = {
  address: string
  name: string
  symbol: string
  logo: string
  price: number
  change5m: number
  change1h: number
  mc: number
  liquidity: number
  volume24h: number
  updatedAt: string
  signals: SignalType[]
  boostCount?: number
  launchpad?: string // Added to support filtering by launchpad (pumpfun, bags, heaven, etc.)
  mint?: string // Mint address
  creator?: string // Creator address
}

export type SignalEvent = {
  id: string
  ts: string
  type: SignalType
  tokenAddress: string
  tokenName: string
  tokenSymbol: string
  tokenLogo: string
  context: string
  mc?: number
  priceChange?: number
  timeframe?: "5m" | "1h" | "24h"
}

// Mock tokens with realistic data
export const tokens: TokenRow[] = [
  {
    address: "0xa1b2c3d4e5f6",
    name: "PepeMax",
    symbol: "PMAX",
    logo: "/pepe-frog-crypto-logo.jpg",
    price: 0.00042,
    change5m: 24.5,
    change1h: 18.3,
    mc: 850000,
    liquidity: 120000,
    volume24h: 450000,
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    signals: ["DEXBOOST_PAID", "PRICE_UP", "KEY_MC"],
    boostCount: 30,
    launchpad: "pumpfun", // Added launchpad property
    mint: "7xKXtLg9vM2nQ8sP1jF3hR9bY2mW5cT6vL8xN9qA1dE3",
    creator: "JHUYx8K2mP9qL7sF3vN6hR4cY1nW5bT8xM9pB2gF5kZQ",
  },
  {
    address: "0xf6e5d4c3b2a1",
    name: "SafeMoon Inu",
    symbol: "SMINU",
    logo: "/moon-dog-crypto-logo.jpg",
    price: 0.000012,
    change5m: -5.2,
    change1h: 8.7,
    mc: 2400000,
    liquidity: 380000,
    volume24h: 1200000,
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    signals: ["DEXAD_PAID", "CTO", "UPDATE_SOCIAL"],
    launchpad: "bags", // Added launchpad property
    mint: "9yHXtLg5vR3pQ4sM8jK7hB2cY6nW9cT4vL2xR5qD8fE1",
    creator: "ALICEp2K8mN6qR9sL3jD7hF5cX1nY4bV9xQ2mB8gT6kZ",
  },
  {
    address: "0x1a2b3c4d5e6f",
    name: "ElonDoge",
    symbol: "EDOGE",
    logo: "/doge-rocket-crypto-logo.jpg",
    price: 0.0089,
    change5m: 145.8,
    change1h: 89.2,
    mc: 5600000,
    liquidity: 890000,
    volume24h: 3400000,
    updatedAt: new Date(Date.now() - 1 * 60000).toISOString(),
    signals: ["DEXBOOST_PAID", "DEXAD_PAID", "ATH", "PRICE_UP"],
    boostCount: 50,
    launchpad: "heaven", // Added launchpad property
    mint: "4kZQrLm8vN7mT9sL3jD6hK5cX2nY8bV7vQ4xM9pB2gF5",
    creator: "BOBKYm5K9pL7sF2jW6hR8cX4nZ1bV5xT9qM3gD8kE7pump",
  },
  {
    address: "0x9f8e7d6c5b4a",
    name: "WojakCoin",
    symbol: "WJK",
    logo: "/wojak-meme-crypto-logo.jpg",
    price: 0.0034,
    change5m: 12.4,
    change1h: 5.8,
    mc: 1800000,
    liquidity: 245000,
    volume24h: 680000,
    updatedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    signals: ["PRICE_UP", "KEY_MC"],
    launchpad: "bags", // Added launchpad property
    creator: "WOJAKp8K2nL5qR9sM7jD4hF2cX9nY6bV3xT8pB5gK1fZ",
  },
  {
    address: "0x3c2b1a9f8e7d",
    name: "BabyFloki",
    symbol: "BFLOKI",
    logo: "/baby-dog-crypto-logo.jpg",
    price: 0.000067,
    change5m: 56.3,
    change1h: 42.1,
    mc: 4200000,
    liquidity: 650000,
    volume24h: 2100000,
    updatedAt: new Date(Date.now() - 3 * 60000).toISOString(),
    signals: ["DEXBAR_PAID", "CTO", "PRICE_UP"],
    launchpad: "pumpfun", // Added launchpad property
    creator: "FLOKIr5K3nM8qL2sP6jW9hB4cY7nX2bV9xT5pK8gF3kZ",
  },
  {
    address: "0x7d6c5b4a3f2e",
    name: "ShibaKing",
    symbol: "SKING",
    logo: "/shiba-crown-crypto-logo.jpg",
    price: 0.0156,
    change5m: -8.9,
    change1h: -12.4,
    mc: 3100000,
    liquidity: 420000,
    volume24h: 980000,
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    signals: ["UPDATE_SOCIAL"],
    launchpad: "bags", // Added launchpad property
    creator: "SKINGm4K7nP2qR6sL9jF5hC8cY3nB6vX1xM7pD9gT4fE",
  },
  {
    address: "0x4e3f2a1b9c8d",
    name: "MoonRocket",
    symbol: "MRKT",
    logo: "/rocket-moon-crypto-logo.jpg",
    price: 0.0245,
    change5m: 89.7,
    change1h: 156.3,
    mc: 7800000,
    liquidity: 920000,
    volume24h: 4800000,
    updatedAt: new Date(Date.now() - 30000).toISOString(),
    signals: ["DEXBOOST_PAID", "ATH", "PRICE_UP", "KEY_MC"],
    boostCount: 100,
    launchpad: "heaven", // Added launchpad property
    creator: "MRKTLp3K8nQ5sR7jM2hF9cX6nY4bV1xT8pG5kD9fE2pump",
  },
  {
    address: "0x8d7c6b5a4e3f",
    name: "DogeKiller",
    symbol: "DKILL",
    logo: "/doge-x-crypto-logo.jpg",
    price: 0.00123,
    change5m: 18.2,
    change1h: 24.7,
    mc: 1450000,
    liquidity: 210000,
    volume24h: 560000,
    updatedAt: new Date(Date.now() - 6 * 60000).toISOString(),
    signals: ["DEXAD_PAID", "PRICE_UP"],
    launchpad: "bags", // Added launchpad property
    creator: "DKILLq7K2nM9pR4sL8jD3hF5cY6nX8bV2xT9pB4gK7fZ",
  },
  {
    address: "0x2e1f9a8b7c6d",
    name: "PumpToken",
    symbol: "PUMP",
    logo: "/pump-chart-crypto-logo.jpg",
    price: 0.0678,
    change5m: 234.5,
    change1h: 189.3,
    mc: 6500000,
    liquidity: 780000,
    volume24h: 3900000,
    updatedAt: new Date(Date.now() - 45000).toISOString(),
    signals: ["DEXBOOST_PAID", "DEXBAR_PAID", "ATH"],
    boostCount: 10,
    launchpad: "pumpfun", // Added launchpad property
    creator: "PUMPXm8K5nL3qR7sM4jW2hF9cY6nB1vT8xP5gK9fD2pump",
  },
  {
    address: "0x5a4e3f2b1c9d",
    name: "GigaChad",
    symbol: "GCHAD",
    logo: "/chad-muscle-crypto-logo.jpg",
    price: 0.00089,
    change5m: -2.3,
    change1h: 4.5,
    mc: 980000,
    liquidity: 145000,
    volume24h: 320000,
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    signals: ["CTO", "UPDATE_SOCIAL"],
    launchpad: "bags", // Added launchpad property
    creator: "GCHADp6K9nQ3sR5jL8hF2cY4nX7bV1xT2pM8gD5kE9fZ",
  },
  {
    address: "0x9c8d7e6f5a4b",
    name: "ApeMaximus",
    symbol: "APEX",
    logo: "/ape-king-crypto-logo.jpg",
    price: 0.0345,
    change5m: 45.8,
    change1h: 67.2,
    mc: 5200000,
    liquidity: 710000,
    volume24h: 2800000,
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    signals: ["DEXAD_PAID", "PRICE_UP", "KEY_MC"],
    launchpad: "heaven", // Added launchpad property
    creator: "APEXKm2K7nP4qR8sL5jF1hC3cY9nB6vX7xM4pD2gT8fE",
  },
  {
    address: "0x6f5e4d3c2b1a",
    name: "DiamondHands",
    symbol: "DMNDS",
    logo: "/diamond-hands-crypto-logo.jpg",
    price: 0.0012,
    change5m: 8.4,
    change1h: 12.9,
    mc: 1120000,
    liquidity: 165000,
    volume24h: 410000,
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    signals: ["CTO"],
    launchpad: "bags", // Added launchpad property
    creator: "DMNDSr8K3nL6qP2sM9jW4hF7cY1nX5bV8xT3pG6kD2fE",
  },
  {
    address: "0x3b2a1f9e8d7c",
    name: "HodlCoin",
    symbol: "HODL",
    logo: "/hodl-hand-crypto-logo.jpg",
    price: 0.00567,
    change5m: 28.9,
    change1h: 35.6,
    mc: 3400000,
    liquidity: 490000,
    volume24h: 1600000,
    updatedAt: new Date(Date.now() - 7 * 60000).toISOString(),
    signals: ["DEXBAR_PAID", "PRICE_UP"],
    launchpad: "pumpfun", // Added launchpad property
    creator: "HODLXm9K4nP7qR1sL6jF3hC5cY8nB2vT9xM1pG7kD4fE",
  },
  {
    address: "0x7e6d5c4b3a2f",
    name: "BullRun",
    symbol: "BULL",
    logo: "/bull-charge-crypto-logo.jpg",
    price: 0.0892,
    change5m: 167.4,
    change1h: 234.8,
    mc: 8200000,
    liquidity: 950000,
    volume24h: 5100000,
    updatedAt: new Date(Date.now() - 90000).toISOString(),
    signals: ["DEXBOOST_PAID", "DEXAD_PAID", "ATH", "KEY_MC"],
    boostCount: 500,
    launchpad: "heaven", // Added launchpad property
    creator: "BULLRm7K1nQ4sP8jL3hF9cY2nX5bV6xT4pM9gK2fD7pump",
  },
  {
    address: "0x1f2e3d4c5b6a",
    name: "MemeLord",
    symbol: "MLORD",
    logo: "/meme-crown-crypto-logo.jpg",
    price: 0.00234,
    change5m: -12.6,
    change1h: -8.3,
    mc: 760000,
    liquidity: 98000,
    volume24h: 280000,
    updatedAt: new Date(Date.now() - 18 * 60000).toISOString(),
    signals: ["UPDATE_SOCIAL"],
    launchpad: "bags", // Added launchpad property
    creator: "MLORDq3K8nL2pR6sM5jF7hC1cY4nX9bV2xT6pG3kD8fE",
  },
  {
    address: "0x8a7b6c5d4e3f",
    name: "RocketMoon",
    symbol: "RMOON",
    logo: "/placeholder.svg?height=32&width=32",
    price: 0.0445,
    change5m: 78.3,
    change1h: 112.7,
    mc: 4900000,
    liquidity: 680000,
    volume24h: 2600000,
    updatedAt: new Date(Date.now() - 2.5 * 60000).toISOString(),
    signals: ["DEXBOOST_PAID", "PRICE_UP", "ATH"],
    boostCount: 30,
    launchpad: "pumpfun", // Added launchpad property
    creator: "RMOONp5K3nM7qL9sR2jF6hC4cY8nB1vT5xP2gD9kE6pump",
  },
  {
    address: "0x4d3c2b1a9f8e",
    name: "SafeRug",
    symbol: "SRUG",
    logo: "/placeholder.svg?height=32&width=32",
    price: 0.000089,
    change5m: 5.2,
    change1h: 8.9,
    mc: 430000,
    liquidity: 62000,
    volume24h: 150000,
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    signals: ["CTO"],
    launchpad: "bags", // Added launchpad property
    creator: "SRUGKm6K1nQ8pR4sL7jF2hC9cY3nX6bV8xT1pM4gD7fE",
  },
  {
    address: "0x9e8f7d6c5b4a",
    name: "WhaleToken",
    symbol: "WHALE",
    logo: "/placeholder.svg?height=32&width=32",
    price: 0.156,
    change5m: 45.6,
    change1h: 67.8,
    mc: 7200000,
    liquidity: 840000,
    volume24h: 4200000,
    updatedAt: new Date(Date.now() - 5.5 * 60000).toISOString(),
    signals: ["DEXAD_PAID", "PRICE_UP", "KEY_MC"],
    launchpad: "heaven", // Added launchpad property
    creator: "WHALEq8K5nL1pR3sM7jF4hC2cY9nX6bV1xT5pG8kD3pump",
  },
]

// Mock signal events
export const events: SignalEvent[] = [
  {
    id: "evt_001",
    ts: new Date(Date.now() - 30000).toISOString(),
    type: "DEXBOOST_PAID",
    tokenAddress: "0x7e6d5c4b3a2f",
    tokenName: "BullRun",
    tokenSymbol: "BULL",
    tokenLogo: "/bull-charge-crypto-logo.jpg",
    context: "DexBoost advertisement activated for 24h campaign",
    mc: 8200000,
  },
  {
    id: "evt_002",
    ts: new Date(Date.now() - 45000).toISOString(),
    type: "ATH",
    tokenAddress: "0x1a2b3c4d5e6f",
    tokenName: "ElonDoge",
    tokenSymbol: "EDOGE",
    tokenLogo: "/doge-rocket-crypto-logo.jpg",
    context: "New all-time high reached at $0.0089",
    mc: 5600000,
    priceChange: 89.2,
    timeframe: "1h",
  },
  {
    id: "evt_003",
    ts: new Date(Date.now() - 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0xa1b2c3d4e5f6",
    tokenName: "PepeMax",
    tokenSymbol: "PMAX",
    tokenLogo: "/pepe-frog-crypto-logo.jpg",
    context: "Price surged 24.5% in the last 5 minutes",
    priceChange: 24.5,
    timeframe: "5m",
  },
  {
    id: "evt_004",
    ts: new Date(Date.now() - 2 * 60000).toISOString(),
    type: "DEXAD_PAID",
    tokenAddress: "0xf6e5d4c3b2a1",
    tokenName: "SafeMoon Inu",
    tokenSymbol: "SMINU",
    tokenLogo: "/moon-dog-crypto-logo.jpg",
    context: "DexAD banner placement secured on homepage",
    mc: 2400000,
  },
  {
    id: "evt_005",
    ts: new Date(Date.now() - 3 * 60000).toISOString(),
    type: "CTO",
    tokenAddress: "0x3c2b1a9f8e7d",
    tokenName: "BabyFloki",
    tokenSymbol: "BFLOKI",
    tokenLogo: "/baby-dog-crypto-logo.jpg",
    context: "Community takeover announced via official channels",
    mc: 4200000,
  },
  {
    id: "evt_006",
    ts: new Date(Date.now() - 4 * 60000).toISOString(),
    type: "KEY_MC",
    tokenAddress: "0x9c8d7e6f5a4b",
    tokenName: "ApeMaximus",
    tokenSymbol: "APEX",
    tokenLogo: "/ape-king-crypto-logo.jpg",
    context: "Crossed $5M market cap milestone",
    mc: 5200000,
  },
  {
    id: "evt_007",
    ts: new Date(Date.now() - 5 * 60000).toISOString(),
    type: "DEXBAR_PAID",
    tokenAddress: "0x3b2a1f9e8d7c",
    tokenName: "HodlCoin",
    tokenSymbol: "HODL",
    tokenLogo: "/hodl-hand-crypto-logo.jpg",
    context: "Featured in DexBar trending section for 12h",
    mc: 3400000,
  },
  {
    id: "evt_008",
    ts: new Date(Date.now() - 6 * 60000).toISOString(),
    type: "UPDATE_SOCIAL",
    tokenAddress: "0x7d6c5b4a3f2e",
    tokenName: "ShibaKing",
    tokenSymbol: "SKING",
    tokenLogo: "/shiba-crown-crypto-logo.jpg",
    context: "Social media links updated with verified badges",
  },
  {
    id: "evt_009",
    ts: new Date(Date.now() - 7 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x8d7c6b5a4e3f",
    tokenName: "DogeKiller",
    tokenSymbol: "DKILL",
    tokenLogo: "/doge-x-crypto-logo.jpg",
    context: "18.2% price increase detected in 5m window",
    priceChange: 18.2,
    timeframe: "5m",
  },
  {
    id: "evt_010",
    ts: new Date(Date.now() - 8 * 60000).toISOString(),
    type: "DEXBOOST_PAID",
    tokenAddress: "0x2e1f9a8b7c6d",
    tokenName: "PumpToken",
    tokenSymbol: "PUMP",
    tokenLogo: "/pump-chart-crypto-logo.jpg",
    context: "DexBoost premium package activated",
    mc: 6500000,
  },
  {
    id: "evt_011",
    ts: new Date(Date.now() - 9 * 60000).toISOString(),
    type: "ATH",
    tokenAddress: "0x2e1f9a8b7c6d",
    tokenName: "PumpToken",
    tokenSymbol: "PUMP",
    tokenLogo: "/pump-chart-crypto-logo.jpg",
    context: "Reached new ATH following DexBoost campaign",
    mc: 6500000,
    priceChange: 234.5,
    timeframe: "5m",
  },
  {
    id: "evt_012",
    ts: new Date(Date.now() - 10 * 60000).toISOString(),
    type: "CTO",
    tokenAddress: "0x6f5e4d3c2b1a",
    tokenName: "DiamondHands",
    tokenSymbol: "DMNDS",
    tokenLogo: "/diamond-hands-crypto-logo.jpg",
    context: "Community voted for CTO governance model",
    mc: 1120000,
  },
  {
    id: "evt_013",
    ts: new Date(Date.now() - 11 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x8a7b6c5d4e3f",
    tokenName: "RocketMoon",
    tokenSymbol: "RMOON",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "Massive 78.3% pump in last 5 minutes",
    priceChange: 78.3,
    timeframe: "5m",
  },
  {
    id: "evt_014",
    ts: new Date(Date.now() - 12 * 60000).toISOString(),
    type: "KEY_MC",
    tokenAddress: "0xa1b2c3d4e5f6",
    tokenName: "PepeMax",
    tokenSymbol: "PMAX",
    tokenLogo: "/pepe-frog-crypto-logo.jpg",
    context: "Approaching $1M market cap threshold",
    mc: 850000,
  },
  {
    id: "evt_015",
    ts: new Date(Date.now() - 13 * 60000).toISOString(),
    type: "DEXAD_PAID",
    tokenAddress: "0x7e6d5c4b3a2f",
    tokenName: "BullRun",
    tokenSymbol: "BULL",
    tokenLogo: "/bull-charge-crypto-logo.jpg",
    context: "Premium DexAD placement for 48h period",
    mc: 8200000,
  },
  {
    id: "evt_016",
    ts: new Date(Date.now() - 14 * 60000).toISOString(),
    type: "UPDATE_SOCIAL",
    tokenAddress: "0x5a4e3f2b1c9d",
    tokenName: "GigaChad",
    tokenSymbol: "GCHAD",
    tokenLogo: "/chad-muscle-crypto-logo.jpg",
    context: "Twitter and Telegram links verified and updated",
  },
  {
    id: "evt_017",
    ts: new Date(Date.now() - 15 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x9e8f7d6c5b4a",
    tokenName: "WhaleToken",
    tokenSymbol: "WHALE",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "Strong buying pressure with 45.6% gain",
    priceChange: 45.6,
    timeframe: "5m",
  },
  {
    id: "evt_018",
    ts: new Date(Date.now() - 16 * 60000).toISOString(),
    type: "DEXBAR_PAID",
    tokenAddress: "0x1a2b3c4d5e6f",
    tokenName: "ElonDoge",
    tokenSymbol: "EDOGE",
    tokenLogo: "/doge-rocket-crypto-logo.jpg",
    context: "Secured top spot in DexBar for 6h",
    mc: 5600000,
  },
  {
    id: "evt_019",
    ts: new Date(Date.now() - 17 * 60000).toISOString(),
    type: "CTO",
    tokenAddress: "0x4d3c2b1a9f8e",
    tokenName: "SafeRug",
    tokenSymbol: "SRUG",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "Development team transferred control to community",
    mc: 430000,
  },
  {
    id: "evt_020",
    ts: new Date(Date.now() - 18 * 60000).toISOString(),
    type: "KEY_MC",
    tokenAddress: "0x1a2b3c4d5e6f",
    tokenName: "ElonDoge",
    tokenSymbol: "EDOGE",
    tokenLogo: "/doge-rocket-crypto-logo.jpg",
    context: "Passed $5M market cap with strong momentum",
    mc: 5600000,
  },
  {
    id: "evt_021",
    ts: new Date(Date.now() - 19 * 60000).toISOString(),
    type: "DEXBOOST_PAID",
    tokenAddress: "0x8a7b6c5d4e3f",
    tokenName: "RocketMoon",
    tokenSymbol: "RMOON",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "DexBoost launch package activated successfully",
    mc: 4900000,
  },
  {
    id: "evt_022",
    ts: new Date(Date.now() - 20 * 60000).toISOString(),
    type: "ATH",
    tokenAddress: "0x8a7b6c5d4e3f",
    tokenName: "RocketMoon",
    tokenSymbol: "RMOON",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "New all-time high following paid promotion",
    mc: 4900000,
    priceChange: 112.7,
    timeframe: "1h",
  },
  {
    id: "evt_023",
    ts: new Date(Date.now() - 21 * 60000).toISOString(),
    type: "UPDATE_SOCIAL",
    tokenAddress: "0x1f2e3d4c5b6a",
    tokenName: "MemeLord",
    tokenSymbol: "MLORD",
    tokenLogo: "/meme-crown-crypto-logo.jpg",
    context: "Website and Discord links added to profile",
  },
  {
    id: "evt_024",
    ts: new Date(Date.now() - 22 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x3b2a1f9e8d7c",
    tokenName: "HodlCoin",
    tokenSymbol: "HODL",
    tokenLogo: "/hodl-hand-crypto-logo.jpg",
    context: "28.9% surge following DexBar feature",
    priceChange: 28.9,
    timeframe: "5m",
  },
  {
    id: "evt_025",
    ts: new Date(Date.now() - 23 * 60000).toISOString(),
    type: "DEXAD_PAID",
    tokenAddress: "0x9e8f7d6c5b4a",
    tokenName: "WhaleToken",
    tokenSymbol: "WHALE",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "Featured DexAD on multiple token pages",
    mc: 7200000,
  },
  {
    id: "evt_026",
    ts: new Date(Date.now() - 24 * 60000).toISOString(),
    type: "KEY_MC",
    tokenAddress: "0x9e8f7d6c5b4a",
    tokenName: "WhaleToken",
    tokenSymbol: "WHALE",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    context: "Surpassed $7M market cap milestone",
    mc: 7200000,
  },
  {
    id: "evt_027",
    ts: new Date(Date.now() - 25 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x3c2b1a9f8e7d",
    tokenName: "BabyFloki",
    tokenSymbol: "BFLOKI",
    tokenLogo: "/baby-dog-crypto-logo.jpg",
    context: "56.3% price jump in last 5m",
    priceChange: 56.3,
    timeframe: "5m",
  },
  {
    id: "evt_028",
    ts: new Date(Date.now() - 26 * 60000).toISOString(),
    type: "DEXBAR_PAID",
    tokenAddress: "0x3c2b1a9f8e7d",
    tokenName: "BabyFloki",
    tokenSymbol: "BFLOKI",
    tokenLogo: "/baby-dog-crypto-logo.jpg",
    context: "Featured in DexBar trending for 24h",
    mc: 4200000,
  },
  {
    id: "evt_029",
    ts: new Date(Date.now() - 27 * 60000).toISOString(),
    type: "CTO",
    tokenAddress: "0xf6e5d4c3b2a1",
    tokenName: "SafeMoon Inu",
    tokenSymbol: "SMINU",
    tokenLogo: "/moon-dog-crypto-logo.jpg",
    context: "Community governance model implemented",
    mc: 2400000,
  },
  {
    id: "evt_030",
    ts: new Date(Date.now() - 28 * 60000).toISOString(),
    type: "ATH",
    tokenAddress: "0x7e6d5c4b3a2f",
    tokenName: "BullRun",
    tokenSymbol: "BULL",
    tokenLogo: "/bull-charge-crypto-logo.jpg",
    context: "Hit new ATH during DexBoost campaign",
    mc: 8200000,
    priceChange: 234.8,
    timeframe: "1h",
  },
  {
    id: "evt_031",
    ts: new Date(Date.now() - 29 * 60000).toISOString(),
    type: "KEY_MC",
    tokenAddress: "0x7e6d5c4b3a2f",
    tokenName: "BullRun",
    tokenSymbol: "BULL",
    tokenLogo: "/bull-charge-crypto-logo.jpg",
    context: "Broke through $8M market cap resistance",
    mc: 8200000,
  },
  {
    id: "evt_032",
    ts: new Date(Date.now() - 30 * 60000).toISOString(),
    type: "UPDATE_SOCIAL",
    tokenAddress: "0xf6e5d4c3b2a1",
    tokenName: "SafeMoon Inu",
    tokenSymbol: "SMINU",
    tokenLogo: "/moon-dog-crypto-logo.jpg",
    context: "All social media links verified and refreshed",
  },
  {
    id: "evt_033",
    ts: new Date(Date.now() - 31 * 60000).toISOString(),
    type: "DEXBOOST_PAID",
    tokenAddress: "0xa1b2c3d4e5f6",
    tokenName: "PepeMax",
    tokenSymbol: "PMAX",
    tokenLogo: "/pepe-frog-crypto-logo.jpg",
    context: "DexBoost marketing campaign started",
    mc: 850000,
  },
  {
    id: "evt_034",
    ts: new Date(Date.now() - 32 * 60000).toISOString(),
    type: "PRICE_UP",
    tokenAddress: "0x9c8d7e6f5a4b",
    tokenName: "ApeMaximus",
    tokenSymbol: "APEX",
    tokenLogo: "/ape-king-crypto-logo.jpg",
    context: "Solid 45.8% gain in 5-minute period",
    priceChange: 45.8,
    timeframe: "5m",
  },
  {
    id: "evt_035",
    ts: new Date(Date.now() - 33 * 60000).toISOString(),
    type: "DEXAD_PAID",
    tokenAddress: "0x8d7c6b5a4e3f",
    tokenName: "DogeKiller",
    tokenSymbol: "DKILL",
    tokenLogo: "/doge-x-crypto-logo.jpg",
    context: "DexAD sidebar placement secured",
    mc: 1450000,
  },
]

export type PrelaunchProject = {
  id: string
  tokenName: string
  tokenSymbol: string
  tokenLogo: string
  devName: string
  devWallet: string
  description: string
  launchDate: string
}

export const mockPrelaunchProjects: PrelaunchProject[] = [
  {
    id: "pre_001",
    tokenName: "SolanaAI",
    tokenSymbol: "SOLAI",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    devName: "CryptoBuilder",
    devWallet: "8xKZ...mN9P",
    description: "AI-powered trading bot for Solana ecosystem with automated portfolio management",
    launchDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "pre_002",
    tokenName: "MoonDog",
    tokenSymbol: "MDOG",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    devName: "DevAlpha",
    devWallet: "9yLM...pQ2R",
    description: "Community-driven meme token with yield farming and staking rewards",
    launchDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "pre_003",
    tokenName: "DeFiMaster",
    tokenSymbol: "DFM",
    tokenLogo: "/placeholder.svg?height=32&width=32",
    devName: "BlockchainPro",
    devWallet: "7wJH...oL3S",
    description: "Next-gen DeFi platform with cross-chain swaps and liquidity aggregation",
    launchDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
